server {
    listen 80;
    server_name dns.YOUR_DOMAIN;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name dns.YOUR_DOMAIN;

    ssl_certificate /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # iOS DoH profile download
    location /ios-doh {
        alias /opt/AdGuardHome/ios_doh_profile.mobileconfig;
        types { application/x-apple-aspen-config mobileconfig; }
        add_header Content-Disposition "attachment; filename=beeralex-doh.mobileconfig";
    }

    location /dns-query {
        proxy_pass http://127.0.0.1:3005/dns-query;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_buffering off;
        
        proxy_redirect ~^https?://[^/]+(:\d+)?/(.*)$ https://$host/$2;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:3005/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_redirect ~^https?://[^/]+(:\d+)?/(.*)$ https://$host/$2;
    }

    location / {
        proxy_pass http://127.0.0.1:3005;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_redirect ~^https?://[^/]+(:\d+)?/(.*)$ https://$host/$2;
    }
}
